name: engineering_thesis
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # internalization helpers
  intl: 0.16.1
  flutter_localizations:
    sdk: flutter

  # ios/android view separation helper
  flutter_platform_widgets: ^0.70.2
  cupertino_icons: ^0.1.3

  # architectural pattern helpers
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0

  # auth helper
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1

  # database helper
  cloud_firestore: ^0.14.3

  # storage helper
  firebase_storage: ^5.2.0

  # env helpers
  meta: ^1.2.3
  equatable: ^1.2.5
  flutter_dotenv: ^2.1.0
  sqflite: ^1.3.2+1
  logger: ^0.9.4

  # files helpers
  file_picker: ^2.1.4

  # images helpers
  transparent_image: ^1.0.0
  image_cropper: ^1.3.1

  # maps helpers
  google_maps_flutter: ^1.0.6
  google_maps_webservice: ^0.0.18
  geohash: ^0.2.1
  google_maps_cluster_manager: ^0.2.0

  # view
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env

# basic internalization settings
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en_US
